apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: website-watcher
type: Opaque
stringData:
  POSTGRES_DB: website_watcher
  POSTGRES_USER: watcher
  POSTGRES_PASSWORD: secret
