apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: website-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: fiziksmen/website-watcher-worker:latest
          envFrom:
            - configMapRef:
                name: worker-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
